In [1]:
import numpy as np

Массив размером 10, заполненный нулями

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Вектор размера 10, заполненный числом 2.5

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [2]:
vector = np.zeros(10)
vector[4] = 1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

 Вектор со значениями от 10 до 49

In [9]:
vector = np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
array = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(array)[0]

array([0, 1, 4])

Единичная матрица 3x3

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Массив 10x10 со случайными значениями, его минимум и максимум

In [3]:
random_array = np.random.randint(0, 100, (10, 10))
print(random_array)
max = random_array.max()
min = random_array.min()
print(f'max: {max}')
print(f'min: {min}')

[[34 47 25 77 45 36 60 57 83 84]
 [14 41 46 72 57  5 19 15 15 96]
 [62 55 71 72 93 91 82 11 72 11]
 [98 44  1 69  1 59 49 60 26  7]
 [32 52 82 13  2 83 95 51 90 87]
 [ 4 18 54 11 69 36 88 29 29 51]
 [84 60 69 71 71 71 80 56  5 15]
 [87 36 59 52 81 26 62 99 30 52]
 [56 55 90 14 10 20 71 20 66 82]
 [27  2 92 56 11 85 95 83  5 84]]
max: 99
min: 1


Случайный вектор размера 30 и его среднее значение всех элементов

In [17]:
vector = np.random.randint(0, 10, 30)
print(vector)
average = vector.mean()
f"Среднее значение: {average}"

[7 4 6 1 5 9 5 6 1 8 3 4 0 9 4 3 1 8 3 8 5 3 0 6 3 4 6 9 6 7]


'Среднее значение: 4.8'

8x8 матрицу и заполнить ее в шахматном порядке

In [19]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Умножение матриц 5x3 и 3x2

In [20]:
matrix1 = np.random.randint(0, 10, (5, 3))
matrix2 = np.random.randint(0, 10, (3, 2))
np.dot(matrix1, matrix2)

array([[ 96,  55],
       [100,  88],
       [132, 105],
       [120,  72],
       [124, 123]], dtype=int32)

Одинаковы ли 2 numpy массива


In [21]:
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])
np.array_equal(array1, array2)

True

Заменить максимальный элемент на ноль


In [22]:
array = np.array([1, 5, 3, 8, 2, 7])
array[array.argmax()] = 0
array

array([1, 5, 3, 0, 2, 7])

Найти наиболее частое значение в массиве

In [23]:
array = np.array([1, 1, 1, 2, 2, 2, 2, 3, 3])
unique, counts = np.unique(array, return_counts=True)
unique[counts.argmax()]

np.int64(2)

Найти n наибольших значений в массиве

In [24]:
n = 4
array = np.array([5, 1, 8, 3, 9, 2, 7, 4, 6])
largest_nums = np.partition(array, -n)[-n:]
largest_nums

array([6, 7, 8, 9])